<<<<<<< HEAD
name: Labeler
on: [pull_request_target]
jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write


    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
=======
name: Labeler
on: [pull_request_target]
jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write


    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
>>>>>>> 0dfbab63a251985517b5c35679c5e90c48cee5c3
